import { Metadata } from "next";
import { notFound } from "next/navigation";
import { ServicePageClient } from "./ServicePageClient";

const services = {
  "ui-ux-design": {
    title: "UI/UX Design",
    description: "Crafting intuitive and visually stunning interfaces that captivate users and drive engagement.",
    longDescription: "We create user-centered designs that combine aesthetics with functionality. Our design process involves deep user research, iterative prototyping, and rigorous testing to ensure every pixel serves a purpose.",
    color: "from-pink-500 to-rose-500",
    icon: "Palette",
    stats: { projects: "50+", satisfaction: "99%", clients: "30+" },
    techStack: [
      { name: "Figma", description: "Collaborative interface design tool", color: "#F24E1E", level: 98 },
      { name: "Adobe XD", description: "Vector-based UI/UX design tool", color: "#FF61F6", level: 95 },
      { name: "Sketch", description: "Digital design platform for Mac", color: "#F7B500", level: 90 },
      { name: "Framer", description: "Interactive prototyping tool", color: "#0055FF", level: 92 },
      { name: "InVision", description: "Digital product design platform", color: "#FF3366", level: 88 },
      { name: "Principle", description: "Animated interface design", color: "#7B68EE", level: 85 },
      { name: "Adobe Illustrator", description: "Vector graphics editor", color: "#FF9A00", level: 95 },
      { name: "Adobe Photoshop", description: "Image editing software", color: "#31A8FF", level: 93 },
      { name: "Zeplin", description: "Design handoff tool", color: "#FDBD39", level: 90 },
      { name: "Miro", description: "Collaborative whiteboard platform", color: "#FFD02F", level: 88 },
      { name: "Maze", description: "User testing platform", color: "#6366F1", level: 85 },
      { name: "Hotjar", description: "Behavior analytics tool", color: "#FF3C00", level: 87 },
    ],
    process: [
      { step: "Research", description: "User interviews, surveys, and competitive analysis" },
      { step: "Information Architecture", description: "Structuring content and navigation flows" },
      { step: "Wireframing", description: "Low-fidelity sketches and layouts" },
      { step: "Visual Design", description: "High-fidelity mockups with brand identity" },
      { step: "Prototyping", description: "Interactive prototypes for testing" },
      { step: "User Testing", description: "Validating designs with real users" },
    ],
  },
  "frontend-development": {
    title: "Frontend Development",
    description: "Building blazing-fast, responsive web applications with modern frameworks and cutting-edge technologies.",
    longDescription: "We specialize in creating performant, accessible, and beautiful web applications using the latest frontend technologies. Our code is clean, maintainable, and optimized for the best user experience.",
    color: "from-blue-500 to-cyan-500",
    icon: "Code2",
    stats: { projects: "100+", performance: "95+", uptime: "99.9%" },
    techStack: [
      { name: "React", description: "JavaScript library for building UIs", color: "#61DAFB", level: 98 },
      { name: "Next.js", description: "React framework for production", color: "#000000", level: 97 },
      { name: "TypeScript", description: "Typed superset of JavaScript", color: "#3178C6", level: 96 },
      { name: "Vue.js", description: "Progressive JavaScript framework", color: "#42B883", level: 92 },
      { name: "Nuxt.js", description: "Vue.js framework", color: "#00DC82", level: 90 },
      { name: "Tailwind CSS", description: "Utility-first CSS framework", color: "#06B6D4", level: 98 },
      { name: "Framer Motion", description: "Animation library for React", color: "#FF0080", level: 95 },
      { name: "Three.js", description: "3D graphics library", color: "#000000", level: 88 },
      { name: "GSAP", description: "Professional animation platform", color: "#88CE02", level: 90 },
      { name: "Redux", description: "State management library", color: "#764ABC", level: 93 },
      { name: "Zustand", description: "Lightweight state management", color: "#453F39", level: 94 },
      { name: "React Query", description: "Data fetching library", color: "#FF4154", level: 95 },
      { name: "GraphQL", description: "Query language for APIs", color: "#E10098", level: 92 },
      { name: "Webpack", description: "Module bundler", color: "#8DD6F9", level: 88 },
      { name: "Vite", description: "Next generation build tool", color: "#646CFF", level: 95 },
      { name: "Jest", description: "JavaScript testing framework", color: "#C21325", level: 90 },
    ],
    process: [
      { step: "Architecture", description: "Planning component structure and state management" },
      { step: "Setup", description: "Project scaffolding and tooling configuration" },
      { step: "Development", description: "Building components with TDD approach" },
      { step: "Integration", description: "Connecting with APIs and backend services" },
      { step: "Testing", description: "Unit, integration, and E2E testing" },
      { step: "Optimization", description: "Performance tuning and bundle optimization" },
    ],
  },
  "backend-development": {
    title: "Backend Development",
    description: "Scalable and secure server-side solutions. APIs, microservices, and robust architectures.",
    longDescription: "We build robust, scalable backend systems that power your applications. From RESTful APIs to complex microservices architectures, we ensure your backend is secure, performant, and maintainable.",
    color: "from-green-500 to-emerald-500",
    icon: "Server",
    stats: { apis: "200+", uptime: "99.9%", requests: "10M+/day" },
    techStack: [
      { name: "Node.js", description: "JavaScript runtime environment", color: "#339933", level: 97 },
      { name: "Express.js", description: "Minimal Node.js framework", color: "#000000", level: 96 },
      { name: "NestJS", description: "Progressive Node.js framework", color: "#E0234E", level: 94 },
      { name: "Python", description: "High-level programming language", color: "#3776AB", level: 95 },
      { name: "Django", description: "Python web framework", color: "#092E20", level: 93 },
      { name: "FastAPI", description: "Modern Python framework", color: "#009688", level: 94 },
      { name: "Go", description: "Statically typed language by Google", color: "#00ADD8", level: 90 },
      { name: "Gin", description: "Go web framework", color: "#00ADD8", level: 88 },
      { name: "PostgreSQL", description: "Advanced SQL database", color: "#4169E1", level: 96 },
      { name: "MongoDB", description: "NoSQL document database", color: "#47A248", level: 94 },
      { name: "Redis", description: "In-memory data store", color: "#DC382D", level: 95 },
      { name: "Prisma", description: "Next-gen Node.js ORM", color: "#2D3748", level: 93 },
      { name: "GraphQL", description: "API query language", color: "#E10098", level: 92 },
      { name: "gRPC", description: "High-performance RPC framework", color: "#244C5A", level: 88 },
      { name: "RabbitMQ", description: "Message broker", color: "#FF6600", level: 90 },
      { name: "Kafka", description: "Distributed streaming platform", color: "#231F20", level: 87 },
    ],
    process: [
      { step: "API Design", description: "RESTful or GraphQL schema design" },
      { step: "Database Design", description: "Schema modeling and optimization" },
      { step: "Authentication", description: "Secure auth flows and JWT implementation" },
      { step: "Business Logic", description: "Core application logic development" },
      { step: "Integration", description: "Third-party services and APIs" },
      { step: "Security", description: "Vulnerability assessment and hardening" },
    ],
  },
  "cloud-solutions": {
    title: "Cloud Solutions",
    description: "Enterprise-grade cloud infrastructure on AWS, GCP, and Azure. Scalable and secure.",
    longDescription: "We design and implement cloud-native solutions that scale with your business. From serverless architectures to container orchestration, we optimize for performance, cost, and reliability.",
    color: "from-orange-500 to-amber-500",
    icon: "Cloud",
    stats: { deployments: "500+", savings: "40%", uptime: "99.99%" },
    techStack: [
      { name: "AWS", description: "Amazon Web Services", color: "#FF9900", level: 97 },
      { name: "AWS Lambda", description: "Serverless compute service", color: "#FF9900", level: 95 },
      { name: "AWS S3", description: "Object storage service", color: "#569A31", level: 97 },
      { name: "AWS EC2", description: "Virtual servers in the cloud", color: "#FF9900", level: 96 },
      { name: "Google Cloud", description: "Google Cloud Platform", color: "#4285F4", level: 93 },
      { name: "Cloud Functions", description: "GCP serverless functions", color: "#4285F4", level: 91 },
      { name: "Azure", description: "Microsoft cloud platform", color: "#0078D4", level: 90 },
      { name: "Azure Functions", description: "Azure serverless compute", color: "#0062AD", level: 88 },
      { name: "Cloudflare", description: "CDN and security platform", color: "#F38020", level: 94 },
      { name: "Vercel", description: "Frontend cloud platform", color: "#000000", level: 96 },
      { name: "Netlify", description: "Web development platform", color: "#00C7B7", level: 93 },
      { name: "DigitalOcean", description: "Cloud infrastructure provider", color: "#0080FF", level: 92 },
      { name: "Supabase", description: "Open source Firebase alternative", color: "#3ECF8E", level: 90 },
      { name: "Firebase", description: "Google's app development platform", color: "#FFCA28", level: 94 },
      { name: "PlanetScale", description: "Serverless MySQL platform", color: "#000000", level: 88 },
      { name: "Upstash", description: "Serverless Redis & Kafka", color: "#00E9A3", level: 87 },
    ],
    process: [
      { step: "Assessment", description: "Current infrastructure analysis" },
      { step: "Architecture", description: "Cloud-native solution design" },
      { step: "Migration", description: "Seamless workload migration" },
      { step: "Optimization", description: "Cost and performance tuning" },
      { step: "Security", description: "IAM, encryption, and compliance" },
      { step: "Monitoring", description: "Observability and alerting setup" },
    ],
  },
  "mobile-development": {
    title: "Mobile Development",
    description: "Native and cross-platform mobile apps delivering exceptional experiences on iOS and Android.",
    longDescription: "We create mobile applications that users love. Whether native or cross-platform, our apps are performant, beautiful, and built to scale with millions of users.",
    color: "from-purple-500 to-violet-500",
    icon: "Smartphone",
    stats: { apps: "30+", downloads: "1M+", rating: "4.8★" },
    techStack: [
      { name: "React Native", description: "Cross-platform framework", color: "#61DAFB", level: 97 },
      { name: "Expo", description: "React Native toolchain", color: "#000020", level: 95 },
      { name: "Flutter", description: "Google's UI toolkit", color: "#02569B", level: 93 },
      { name: "Swift", description: "iOS programming language", color: "#F05138", level: 90 },
      { name: "SwiftUI", description: "Declarative iOS framework", color: "#F05138", level: 88 },
      { name: "Kotlin", description: "Android programming language", color: "#7F52FF", level: 90 },
      { name: "Jetpack Compose", description: "Android UI toolkit", color: "#4285F4", level: 87 },
      { name: "Firebase", description: "Mobile backend platform", color: "#FFCA28", level: 95 },
      { name: "Realm", description: "Mobile database", color: "#39477F", level: 88 },
      { name: "SQLite", description: "Embedded database", color: "#003B57", level: 90 },
      { name: "RevenueCat", description: "In-app subscriptions", color: "#FF6363", level: 85 },
      { name: "OneSignal", description: "Push notifications", color: "#E54B4D", level: 90 },
      { name: "Sentry", description: "Error tracking", color: "#362D59", level: 92 },
      { name: "Fastlane", description: "App deployment automation", color: "#00F0FF", level: 88 },
      { name: "App Center", description: "Microsoft mobile DevOps", color: "#CB2E6D", level: 85 },
      { name: "TestFlight", description: "iOS beta testing", color: "#0D96F6", level: 93 },
    ],
    process: [
      { step: "Discovery", description: "Platform strategy and requirements" },
      { step: "Design", description: "Mobile-first UI/UX design" },
      { step: "Development", description: "Native or cross-platform coding" },
      { step: "Testing", description: "Device testing and QA" },
      { step: "Deployment", description: "App store submission and release" },
      { step: "Analytics", description: "User behavior and crash reporting" },
    ],
  },
  "devops-cicd": {
    title: "DevOps & CI/CD",
    description: "Streamlined development workflows with automated testing, deployment, and monitoring.",
    longDescription: "We implement DevOps practices that accelerate your development lifecycle. From continuous integration to continuous deployment, we automate everything for faster, safer releases.",
    color: "from-red-500 to-orange-500",
    icon: "GitBranch",
    stats: { pipelines: "150+", faster: "80%", incidents: "-70%" },
    techStack: [
      { name: "Docker", description: "Container platform", color: "#2496ED", level: 97 },
      { name: "Kubernetes", description: "Container orchestration", color: "#326CE5", level: 94 },
      { name: "Helm", description: "Kubernetes package manager", color: "#0F1689", level: 90 },
      { name: "GitHub Actions", description: "CI/CD automation", color: "#2088FF", level: 96 },
      { name: "GitLab CI", description: "GitLab CI/CD pipelines", color: "#FC6D26", level: 93 },
      { name: "Jenkins", description: "Automation server", color: "#D24939", level: 90 },
      { name: "CircleCI", description: "Continuous integration", color: "#343434", level: 88 },
      { name: "Terraform", description: "Infrastructure as code", color: "#7B42BC", level: 95 },
      { name: "Pulumi", description: "Modern IaC platform", color: "#8A3391", level: 88 },
      { name: "Ansible", description: "Configuration management", color: "#EE0000", level: 90 },
      { name: "ArgoCD", description: "GitOps CD tool", color: "#EF7B4D", level: 87 },
      { name: "Prometheus", description: "Monitoring system", color: "#E6522C", level: 92 },
      { name: "Grafana", description: "Observability platform", color: "#F46800", level: 94 },
      { name: "Datadog", description: "Monitoring & analytics", color: "#632CA6", level: 90 },
      { name: "New Relic", description: "Observability platform", color: "#008C99", level: 88 },
      { name: "Vault", description: "Secrets management", color: "#000000", level: 85 },
    ],
    process: [
      { step: "Assessment", description: "Current workflow analysis" },
      { step: "Pipeline Design", description: "CI/CD architecture planning" },
      { step: "Containerization", description: "Docker and orchestration setup" },
      { step: "Automation", description: "Build, test, deploy automation" },
      { step: "Monitoring", description: "Observability stack implementation" },
      { step: "Optimization", description: "Continuous improvement" },
    ],
  },
  "gpu-ai-solutions": {
    title: "GPU & AI Solutions",
    description: "Harness the power of GPU computing and AI/ML for intelligent applications.",
    longDescription: "We leverage cutting-edge AI and GPU technologies to build intelligent applications. From custom ML models to LLM integrations, we bring the power of AI to your products.",
    color: "from-yellow-500 to-lime-500",
    icon: "Cpu",
    stats: { models: "25+", accuracy: "95%", inference: "<100ms" },
    techStack: [
      { name: "PyTorch", description: "Deep learning framework", color: "#EE4C2C", level: 95 },
      { name: "TensorFlow", description: "ML platform by Google", color: "#FF6F00", level: 93 },
      { name: "OpenAI API", description: "GPT and DALL-E APIs", color: "#412991", level: 97 },
      { name: "Anthropic Claude", description: "AI assistant API", color: "#D4A27F", level: 95 },
      { name: "Hugging Face", description: "ML model hub", color: "#FFD21E", level: 94 },
      { name: "LangChain", description: "LLM application framework", color: "#1C3C3C", level: 93 },
      { name: "Pinecone", description: "Vector database", color: "#000000", level: 90 },
      { name: "Weaviate", description: "Vector search engine", color: "#01B386", level: 88 },
      { name: "CUDA", description: "NVIDIA GPU computing", color: "#76B900", level: 88 },
      { name: "JAX", description: "High-performance ML", color: "#A855F7", level: 85 },
      { name: "scikit-learn", description: "ML library for Python", color: "#F7931E", level: 92 },
      { name: "Pandas", description: "Data analysis library", color: "#150458", level: 95 },
      { name: "NumPy", description: "Numerical computing", color: "#013243", level: 96 },
      { name: "FastAPI", description: "ML model serving", color: "#009688", level: 94 },
      { name: "MLflow", description: "ML lifecycle platform", color: "#0194E2", level: 88 },
      { name: "Weights & Biases", description: "ML experiment tracking", color: "#FFBE00", level: 90 },
    ],
    process: [
      { step: "Problem Definition", description: "Understanding ML requirements" },
      { step: "Data Pipeline", description: "Collection and preprocessing" },
      { step: "Model Development", description: "Training and fine-tuning" },
      { step: "Evaluation", description: "Performance benchmarking" },
      { step: "Deployment", description: "Model serving infrastructure" },
      { step: "Monitoring", description: "Drift detection and retraining" },
    ],
  },
  "deployment-hosting": {
    title: "Deployment & Hosting",
    description: "Zero-downtime deployments and managed hosting. Your applications, always online.",
    longDescription: "We ensure your applications are always available with enterprise-grade hosting and deployment solutions. From CDN configuration to auto-scaling, we handle it all.",
    color: "from-teal-500 to-cyan-500",
    icon: "Rocket",
    stats: { sites: "200+", uptime: "99.99%", speed: "<200ms" },
    techStack: [
      { name: "Vercel", description: "Frontend deployment platform", color: "#000000", level: 98 },
      { name: "Netlify", description: "Web development platform", color: "#00C7B7", level: 95 },
      { name: "Railway", description: "Infrastructure platform", color: "#0B0D0E", level: 92 },
      { name: "Render", description: "Cloud application platform", color: "#46E3B7", level: 90 },
      { name: "Fly.io", description: "Global app platform", color: "#8B5CF6", level: 88 },
      { name: "DigitalOcean", description: "Cloud infrastructure", color: "#0080FF", level: 93 },
      { name: "AWS Amplify", description: "Full-stack deployment", color: "#FF9900", level: 90 },
      { name: "Heroku", description: "Cloud platform", color: "#430098", level: 88 },
      { name: "Cloudflare Pages", description: "JAMstack platform", color: "#F38020", level: 92 },
      { name: "GitHub Pages", description: "Static site hosting", color: "#181717", level: 90 },
      { name: "Nginx", description: "Web server", color: "#009639", level: 95 },
      { name: "Caddy", description: "Modern web server", color: "#00ADD8", level: 88 },
      { name: "PM2", description: "Node.js process manager", color: "#2B037A", level: 93 },
      { name: "Docker Compose", description: "Multi-container Docker", color: "#2496ED", level: 94 },
      { name: "Traefik", description: "Cloud native proxy", color: "#24A1C1", level: 87 },
      { name: "Let's Encrypt", description: "Free SSL certificates", color: "#003A70", level: 95 },
    ],
    process: [
      { step: "Infrastructure", description: "Hosting environment setup" },
      { step: "CI/CD", description: "Automated deployment pipeline" },
      { step: "SSL/CDN", description: "Security and performance" },
      { step: "Monitoring", description: "Uptime and performance tracking" },
      { step: "Scaling", description: "Auto-scaling configuration" },
      { step: "Backup", description: "Disaster recovery planning" },
    ],
  },
};

export async function generateStaticParams() {
  return Object.keys(services).map((slug) => ({ slug }));
}

export async function generateMetadata({ params }: { params: { slug: string } }): Promise<Metadata> {
  const service = services[params.slug as keyof typeof services];
  
  if (!service) {
    return { title: "Service Not Found" };
  }

  return {
    title: `${service.title} Services`,
    description: service.description,
    openGraph: {
      title: `${service.title} - CodeMasheen`,
      description: service.description,
    },
  };
}

export default function ServicePage({ params }: { params: { slug: string } }) {
  const service = services[params.slug as keyof typeof services];
  
  if (!service) {
    notFound();
  }

  return <ServicePageClient service={service} slug={params.slug} />;
}

